In [18]:
#ONE DIMENSTIONAL ARRAY

In [22]:
import numpy as np
list1=[1,2,3,4]
arr1=np.array(list1)
print(arr1)
print(arr1.ndim)

[1 2 3 4]
1


In [4]:
list1=[1,2,3,4]


[2 4 6 8]


In [5]:
print(list1*2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [6]:
type(arr1)

numpy.ndarray

In [20]:
arr2=np.array([10,20,30,40])
print(arr2)
arr2.shape

[10 20 30 40]


(4,)

In [ ]:
#TWO DIMENSIONAL ARRAY

In [23]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr3)
print(arr3.ndim)
print(arr3.size)
print(arr3.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
12
(4, 3)


In [9]:
arr4=np.array([[12,13,14],[14,15,16]])
print(arr4)
print(arr4.size)

[[12 13 14]
 [14 15 16]]
6


In [ ]:
#THREE DIMENSIONAL ARRAY

In [14]:
arr5=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,15,20],[30,40,50],[60,70,80]],[[34,56,78],[18,19,20],[22,33,44]]])
print(arr5)
print(arr5.ndim)
print(arr5.size)
print(arr5.shape)



[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 15 20]
  [30 40 50]
  [60 70 80]]

 [[34 56 78]
  [18 19 20]
  [22 33 44]]]
3
27
(3, 3, 3)


In [19]:
#RESHAPE AN ARRAY

In [24]:
#1D TO 2D ARRAY

In [26]:
arr6=arr1.reshape(2,2)
print(arr6)

[[1 2]
 [3 4]]


In [ ]:
#1D TO 3D ARRAY

In [31]:
arr7=np.array([1,2,3,4,5,6,7,8])
arr8=arr7.reshape(2,2,2)
print(arr8)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#2D TO 3D ARRAY

In [34]:
arr8=np.array([[1,2],[3,4],[5,6],[6,7]])
arr9=arr8.reshape(2,2,2)
print(arr9)

[[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]


In [ ]:
#2D TO 2D ARRAY

In [37]:
arr10=arr8.reshape(2,4)
print(arr10)

[[1 2 3 4]
 [5 6 6 7]]


In [ ]:
#3D TO 3D ARRAY

In [41]:
arr11=arr5.reshape(1,9,3)
print(arr11)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 15 20]
  [30 40 50]
  [60 70 80]
  [34 56 78]
  [18 19 20]
  [22 33 44]]]


In [42]:
arr12=arr4.reshape(-1)
print(arr12)

[12 13 14 14 15 16]


In [ ]:
#FIND DATA TYPES OF AN ARRAY

In [3]:
import numpy as np
arr13=np.array([1,2,3,4,5,])
print(arr13.dtype)
arr14=np.array([1.2,2.2,3.3,4.4])
print(arr14.dtype)
arr15=np.array(['a','b','c','d','e'])
print(arr15.dtype)

int32
float64
<U1


In [ ]:
#CREATE AN ARRAY WITH SPECIFIC OF DATATYPE

In [5]:
import numpy as np
arr16=np.array([1,2,3,4,5],dtype=np.float16)
print(arr16)
print(arr16.dtype)

[1. 2. 3. 4. 5.]
float16


In [8]:
import numpy as np
arr17=np.array([1.1,2.2,3.3,4.4,5.5],dtype=np.int32)
print(arr17)
print(arr17.dtype)

[1 2 3 4 5]
int32


In [ ]:
#HOW TO CONVERT AN ARRAY TO ANOTHER DATATYPE

In [15]:
import numpy as np
arr18=np.array([1,2,3,4,5],dtype=np.int8)
arr19=arr18.astype(np.float16)
print(arr19)
print(arr19.dtype)

[1. 2. 3. 4. 5.]
float16


In [ ]:
#ARRAY CREATION METHOD

In [ ]:
#numpy.array()

In [17]:
arr20=np.array([1,2,3,4])
print(arr20)

[1 2 3 4]


In [ ]:
#NUMPY.ZEROS()

In [19]:
arr21=np.zeros(6)
print(arr21)

[0. 0. 0. 0. 0. 0.]


In [21]:
arr22=np.zeros((4,4))
print(arr22)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
arr23=np.zeros(((2,4,4)))
print(arr23)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
#numpy.ones()

In [26]:
arr24=np.ones((2,4,4))
print(arr24)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
#numpy.arange()

In [31]:
arr25=np.arange(10)
print(arr25)

[0 1 2 3 4 5 6 7 8 9]


In [33]:
arr26=np.arange(1,11)
print(arr26)

[ 1  2  3  4  5  6  7  8  9 10]


In [34]:
arr27=np.arange(10,27)
print(arr27)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]


In [35]:
arr28=np.arange(10,29,2)
print(arr28)

[10 12 14 16 18 20 22 24 26 28]


In [ ]:
#numpy.linspace()

In [36]:
arr29=np.linspace(1,10,5)
print(arr29)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
#numpy.eye()

In [37]:
arr30=np.eye(4)
print(arr30)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [38]:
arr31=np.eye(6,4)
print(arr31)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [39]:
arr32=np.eye(6,4,1)
print(arr32)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [40]:
arr33=np.eye(6,4,2)
print(arr33)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [41]:
arr34=np.eye(6,4,-1)
print(arr34)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [ ]:
#numpy.full()

In [43]:
arr35=np.full(5,12)
print(arr35)

[12 12 12 12 12]


In [45]:
arr36=np.full((3,5),13)
print(arr36)

[[13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]]


In [ ]:
#numpy.random.randint()


In [51]:
arr37=np.random.randint(0,11,(2,2))
print(arr37)

[[ 1 10]
 [ 8  9]]


In [53]:
arr38=np.random.randint(0,100,((2,2,2)))
print(arr38)

[[[63  9]
  [90 37]]

 [[79  7]
  [ 6 39]]]


In [ ]:
#numpy.random.random()

In [55]:
arr39=np.random.random(4)
print(arr39)

[0.18559159 0.73719787 0.49942327 0.3587865 ]


In [57]:
arr40=np.random.random((2,2))
print(arr40)

[[0.9634226  0.94778752]
 [0.66682234 0.62878752]]
